
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 23 09:43:45 CST 2024
//----------------------------------------------------

package Programas.ASAP;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INTEGER = 6;
  public static final int COLON = 3;
  public static final int BOOLEAN = 7;
  public static final int EOF = 0;
  public static final int VAR = 2;
  public static final int ID = 8;
  public static final int error = 1;
  public static final int COMMA = 5;
  public static final int SEMICOLON = 4;
}

