
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 23 20:13:23 CST 2024
//----------------------------------------------------

package Programas.ASAP;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSP = 3;
  public static final int COMA = 5;
  public static final int INTEGER = 6;
  public static final int BOOLEAN = 7;
  public static final int EOF = 0;
  public static final int VAR = 2;
  public static final int ID = 8;
  public static final int error = 1;
  public static final int PYCOMA = 4;
}

